### ISSUE TITLE
Strange and unhelpful output when PyShEx fails

### ISSUE THREAD

**Issue by vemonet** [hsolbrig/PyShEx#25]
I am trying to validate my model using PyShEx on the same data serialized in turtle and JSON-LD.

The only difference is that the JSON-LD file contain the graph information. Those 2 files can be downloaded here: http://graphdb.dumontierlab.com/graphs by exporting the http://data2services/biolink/drugbank

We are using the following shex schema to validate it: https://github.com/biolink/biolink-model/blob/master/shex/biolink-model.shex

Running it with the following commandline:
`shexeval -f json-ld /pathto/181121-biolink-drugbank.jsonld /pathto/biolink-model/shex/biolink-model.shex`

* For JSON-LD it runs for 5 minutes then stops without providing any output
* For Turtle I got 500k lines of the following message: `Error:   START node is not specified or is invalid`

I did a quick validation of the turtle RDF using rapper (just to make sure URIs are fine and there is not syntax error) 

Is it normal to have such output? Especially when the content is exactly the same

**Comment by hsolbrig** [comment]
Apologies for the output -- give me a couple more days to play with the drugbank data. Will get back to you on the slack channel
